### ISSUE TITLE
Feature/Easter egg: incorporate random.codes

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python.org#116]
@MridulS has made a really fun feature at randomsource.codes that drops you into a web editor in a random source file from one of the core scientific Python ecosystem projects. It's sort of like a "review a random file" feature akin to Wikipedia's "random article" button.

This might be a fun feature to add to the site somewhere!

**Comment by stefanv** [comment]
I was chatting to Ross about this, and I think it would be great if we could redirect to a random issue or PR.  That way, the person does not generate a new PR but helps us handle old ones!  Thoughts?

**Comment by MridulS** [comment]
I like this idea too! I have deployed a new app to review random open issues/pr, it redirects to a random issue or PR 

Can be accessed via [review.randomsource.codes](https://review.randomsource.codes). It currently only fetches the latest 300 open issues/PR for a project as GitHub API limits to 100 responses in one call and with some projects this means it needs to make 30-35 calls, which takes up a lot of time. I'll work on it to make the user experience (wrt time to redirection) a bit better.

**Comment by stefanv** [comment]
Nice, I enjoyed playing with the latest version!

**Comment by MridulS** [comment]
Also I think this kind of goes along what folks at https://closember.org want to do too (?), maybe I should chat with them too.

Also now folks can randomise issues in one specific repo if they want to specifically look at one project, like https://review.randomsource.codes/numpy/numpy

**Comment by stefanv** [comment]
@MridulS Could we add an option to only do issues or PRs?  Say https://review.randomsource.codes/numpy/numpy/issues vs https://review.randomsource.codes/numpy/numpy/pulls  Translating to "Solve a random problem" vs "Review a random piece of work"

**Comment by MridulS** [comment]
Don't have the domain name anymore :/ It was 60$ to renew 🤷‍♂️
