### ISSUE TITLE
CI Improvement: Prevent lighthouse failure from blocking the deploy preview

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python.org#260]
I recently [ran into an issue](https://github.com/scientific-python/scientific-python.org/pull/259#issuecomment-1179690335) where I was getting intermittent/arbitrary failures in the "performance" metric from lighthouse. The problem with this is that lighthouse failures cause the entire netlify CI run to fail, which prevents the preview from deploying (AFAICT). I think it'd be an improvement if lighthouse failures could be treated as non-blocking; i.e. have the site preview still deploy when the build is successful, even if lighthouse fails.

**Comment by jarrodmillman** [comment]
This started recently and I am not sure why the performance metric has been so inconsistent. I am looking into it and will let you know what I find. (I've only noticed it happening on PRs. I haven't seen it happen when a PR is merged into main.)

**Comment by jarrodmillman** [comment]
I was able to upgrade it to 3.0.1 (see #269). I have some follow-up still to do, but hopefully the PR noise will be gone now.
