### ISSUE TITLE
Scientific Python BOF shirts!

### ISSUE THREAD

**Issue by juanis2112** [scientific-python/scientific-python.org#264]
Leave a comment on this issue if you'd like to be part of the shirt raffle at SciPy 2022. Please specify your shirt size and if you prefer FEMALE (V-neck), or MALE (crew-neck) shirt.

**Comment by HaoZeke** [comment]
I'd prefer a large male variant. :)

**Comment by mgrover1** [comment]
Count me in :) - Male XXL

**Comment by adelavega** [comment]
!! Male M

**Comment by tkoyama010** [comment]
Male M

**Comment by crazy4pi314** [comment]
V-neck XXL or crew XL 🙏

**Comment by jpivarski** [comment]
Male M, if available. (Thanks!)

**Comment by AmadiGabriel** [comment]
Large Male.

**Comment by jcusick13** [comment]
Men's small! 🙏
