### ISSUE TITLE
New category for the PyAOS community

### ISSUE THREAD

**Issue by DamienIrving** [scientific-python/scientific-python.org#292]
I'm the coordinator of the PyAOS (Python for Atmosphere and Ocean Science; https://pyaos.github.io/) community and for some time now we've been looking for a replacement for our current mailing list. A discourse category is exactly what we're looking for and would love to host it at https://discuss.scientific-python.org if possible?

Here's the source repository (with license): https://github.com/PyAOS/pyaos.github.io

**Comment by jarrodmillman** [comment]
![screenshot](https://user-images.githubusercontent.com/123428/184110406-2e9df3a1-aa45-4089-a890-243d336bbff4.png)

See https://discuss.scientific-python.org/c/contributor/pyaos/28. You may want to edit the about this category post:
https://discuss.scientific-python.org/t/about-the-pyaos-category/398. Let me know if you need any additional privileges or would like me to change anything.

This email address should work: pyaos@discuss.scientific-python.org

**Comment by DamienIrving** [comment]
Thanks, @jarrodmillman. This is great. Thanks for setting it up.
