### ISSUE TITLE
Shorter name for branding

### ISSUE THREAD

**Issue by pllim** [scientific-python/scientific-python.org#329]
### Please describe the new feature.

At NumFOCUS Summit 2022, someone commented that "Scientific Python" is a mouthful and would be nice to have a shorter brand name people can use verbally. Someone (sorry, I forgot who) suggested "SPP" (I also forgot what the second P stands for, sorry).

However, SPP has a bitter taste for some astronomers because it is a language used in the now-almost-defunct IRAF. It was not the most fun language you had to program in (though you will never forget it once you do).

This issue is hopefully for people to brainstorm for more ideas.

### Add any other context about the new feature here, screenshots, etc.

It is unfortunate that "scipy" is already taken. 😉

**Comment by bsipocz** [comment]
for what it's worth, I like "Scientific Python" as the short for "Scientific Python Ecosystem". It's explicit and open to no confusion whether we mean about a library or a conference or an organization.

**Comment by tupui** [comment]
> It is unfortunate that "scipy" is already taken. 😉

Well, what if we could changed that 😉 I am almost not joking. I always felt we should separate the submodules into smaller units. Anyway digressing here haha.

**Comment by bsipocz** [comment]
(and with nice explicit name we are not opening up to silly debates of how it should be pronounced, and I feel are also more welcoming for including people from non English speaking countries, or maybe it's just me who has issues with abbreviations and short stuff that are supposed to be a trivial version for something long)

**Comment by stefanv** [comment]
Thanks all for your feedback, and thank you for raising the issue @pllim. I'm going to close it for now, but we can return to the discussion any time a good alternative comes up.

**Comment by pllim** [comment]
No worries! I am just opening issue about things from the summit before I forget about them. Thanks for humoring my request!

**Comment by stefanv** [comment]
> No worries! I am just opening issue about things from the summit before I forget about them. Thanks for humoring my request!

That's awesome; I appreciate you following up!
