### ISSUE TITLE
Header spacing off

### ISSUE THREAD

**Issue by stefanv** [scientific-python/scientific-python.org#346]
### Please describe the bug or issue including how to reproduce it.

The header spacing on, e.g., https://scientific-python.org/code_of_conduct/ is inconsistent.

**Comment by bsipocz** [comment]
I think the header spacing is consistent, the seemingly inconsistent spacing for "Diversity statement" is rather due to the previous section ending with a list that comes with its own added spacing (see the extra spacing in "Incident reporting resolution and enforcement")

**Comment by stefanv** [comment]
Documents that start headings with `<h2>` are rendered correctly; if multiple `<h1>` headers are present, the documents don't look quite right.
