### ISSUE TITLE
HUGO_VERSION is defined in multiple files

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python.org#376]
### Please describe the bug or issue including how to reproduce it.

The variable is defined at multiple places with different values, not clear which one is to be updated along with e.g. the theme, etc.

```
netlify.toml:  HUGO_VERSION = "0.110.0"
content/specs/netlify.toml:  HUGO_VERSION = "0.103.1"
themes/scientific-python-hugo-theme/doc/netlify.toml:  HUGO_VERSION = "0.104.3"
```

**Comment by stefanv** [comment]
Three different websites that haven't been synced (when `specs` get deployed, they are built as part of `scientific-python.org`, AFAIK). I'd just put them all on 0.111.3, thanks!

**Comment by bsipocz** [comment]
OK, I'll do the update in a separate PR and also update the submodule's version (so I get the fix for the links for my browser :) )

**Comment by bsipocz** [comment]
Oh, ok, I haven't realized that content/specs is also a submodule.

**Comment by jarrodmillman** [comment]
The duplicates are from submodules and used for different builds:
- https://scientific-python.org/
- https://theme.scientific-python.org/

And for building the SPEC previews.
