### ISSUE TITLE
Make a machine readable list of core packages

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python.org#393]
Would be nice to have just a simple list of the core packages

**Comment by tupui** [comment]
I still have in mind the idea I pitched last year at SciPy2022 about having a dynamic deck card UI reading up JSON and rendering them.

cc @Carreau

Would be happy to discuss a bit all of that.

**Comment by Carreau** [comment]
It looks like hugo support custom output, I'm guessing we can do so and expose the list of package as JSON either here or in the spec directory. I've spent some time trying to do it, but without success.

**Comment by stefanv** [comment]
@Carreau I may be able to help: do you want to generate the cards in SVG format at website render time, and then publish the data alongside it?

**Comment by Carreau** [comment]
My idea was to look at wether we could expose some information both in json form. Like have `https://scientific-python.org/core-packages.json` that would be generated at build time.

And Yes maybe have a `https://scientific-python.org/core-packages.html` with cards/logo from all the core packages. I'm guessing I can do that outside hugo in the Makefiel.

**Comment by stefanv** [comment]
That shouldn't be too hard; what information do you need in the json?

**Comment by bsipocz** [comment]
Oh, this dived into the deep end quickly. Originally I needed this list for generating a list like this: https://github.com/scientific-python/specs/issues/183, but could also use a list if we ever need to go and loop through all to open an issue or anything. 

So, I don't need anything complicated, a way to get the name and github URL would be sufficient.
