### ISSUE TITLE
Feature: automate submodule updates

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/scientific-python.org#408]
This came up in discord, that updates to e.g. specs should trigger a rebuild here, or to be super safe, a PR.

**Comment by bsipocz** [comment]
I'm interested in solving this little puzzle, but not sure I can get to it while catching up with work post the summit this week, so if someone beat me to it, please ping me so we don't duplicate efforts.

**Comment by bsipocz** [comment]
Submodules are updated daily, and one can trigger a manual update when it's not enough, so I'm closing this now.

**Comment by stefanv** [comment]
I've been updating using git. Is there another mechanism to trigger dependabot?
