### ISSUE TITLE
AB project pages

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python.org#42]
As an example, I added [specs/meta-spec-0002/networkx.md](https://github.com/scientific-python/specs/blob/master/meta-spec-0002/networkx.md) using [specs/meta-spec-0002/register.py](https://github.com/scientific-python/specs/blob/master/meta-spec-0002/register.py).

- [x] In [build artifact spec page](https://87-327679346-gh.circle-artifacts.com/0/tmp/scientific-python.org/public/specs.html),
![screenshot](https://user-images.githubusercontent.com/123428/104682169-e6b44380-56a8-11eb-9b42-7955735141ae.png)
NetworkX shouldn't be in the list.  That table should only list ``specs/*.md`` files, but shouldn't include markdown files in subdirectories.

- [x] The AB project pages need specialized processing and they have different headers.  For example, [specs/meta-spec-0002/networkx.html](https://87-327679346-gh.circle-artifacts.com/0/tmp/scientific-python.org/public/specs/meta-spec-0002/networkx.html) currently looks like 
![screenshot](https://user-images.githubusercontent.com/123428/104682526-bae58d80-56a9-11eb-8851-3fc5f9075eac.png)
But, the gray box should include the project header fields instead of the spec header fields.

- [x] In [specs/meta-spec-0002.html](https://87-327679346-gh.circle-artifacts.com/0/tmp/scientific-python.org/public/specs/meta-spec-0002.html),
![screenshot](https://user-images.githubusercontent.com/123428/104682735-39422f80-56aa-11eb-9dc8-23bc8745433b.png)
The gray box should have a field projects with ``NetworkX`` listed as a link to  [specs/meta-spec-0002/networkx.html](https://87-327679346-gh.circle-artifacts.com/0/tmp/scientific-python.org/public/specs/meta-spec-0002/networkx.html).  In general, it should include a comma separated list of project names that link to  ``specs/meta-spec-0002/<project>.html``.

**Comment by stefanv** [comment]
The project files live in a different directory currently; are you suggesting that we move them into the SPECs repo?

**Comment by jarrodmillman** [comment]
Yes, they were never meant to live under projects.  The project directory should be removed.  The AB project pages are supposed to be created in ``specs/meta-spec-0002`` when they register as part of the `specs/meta-spec-0002`` process as described in ``specs/meta-spec-0002.md``.  The project pages are ancillary files for ``specs/meta-spec-0002.md`` and reviewed as part of the ``spec`` process.

We could put something on the ``scientific-python.org`` site, but we should discuss that later.  However, I am not convinced we want to do that.

**Comment by stefanv** [comment]
I think this has all been addressed now; can you please verify?
