### ISSUE TITLE
ENH: Add a glossary and table of acronyms

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python.org#53]
It would be nice to have a glossary page with definitions for common terms/phrases and a listing of acronyms. Potential entries might include:
 - scientific Python ecosystem
 - SPEC
 - MetaSPEC
 - SSC
 - Core Projects

Originally mentioned in scientific-python/specs#50 but raising here for visibility.

**Comment by jarrodmillman** [comment]
Addressed in https://github.com/scientific-python/specs/pull/55 and https://github.com/scientific-python/specs/pull/58.
Description list css fixed in #60.
