### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python.org#59]
We need to cleanup a few things leftover from #58 and https://github.com/scientific-python/specs/pull/55.

- [x] Project Gallery. I copied and minimally changed people gallery.  This needs to be cleaned up.  For example, maybe we should have a logo instead of an avatar.  Do we still want to have core projects register (w/ file in core-projects)?  If so, should we autocreate the gallery (maybe just listing the project order?)?  Basically, how should we avoid having to update two things to add / remove core projects? Maybe we only need project name, logo, and github page for project registration....
- [x] People Gallery.  Maybe we should register SSC members in a directory.  And autocreate SSC gallery in MetaSPEC1.  This might be useful if we want to have the SSC listed elsewhere (e.g., on the main site about page under people?).
- [x] General Gallery.  Currently you need to manually layout the grid.  Maybe we could have something that intelligently decides the grid layout.  Should we link to github and homepage?  I like this contributor gallery:  https://nteract.io/about  They have logo/avatar, name, github, and homepage (optional).   This makes sense for projects and people galleries.  If we have separate icon for github and homepage for projects, we could have the logo/name link to the core-projects page w/ endorsed_specs listed.
- [x] Metaspec header.  Remove discussion field.
- [x] If we have logos for projects, maybe we should use them instead of the names for `endorsed_by` displays with hoover that reveals names.  Clicking on the logo should probably still link to  core-projects page w/ endorsed_specs listed.

**Comment by jarrodmillman** [comment]
I didn't like how definition lists were rendered, so I changed it in #60.

**Comment by jarrodmillman** [comment]
@stefanv I updated the specs repo and made a small update to this repo.  I used the new gallery for the steering committee and created a `specs/steering-committee/registers.py` and added `matthias_bussonnier.md`. 

Some remaining issues:

- [ ] `specs/purpose-and-process/index.md` is rendered with its title and header, but the rendered versions of `specs/steering-committee/_index.md` and `specs/core-projects/_index.md` are missing their titles and headers.
- [ ] (low priority and maybe worth discussing) the links for the steering committee members should take you to their homepage or maybe like the nteract gallery I pointed to above they could have a link to github and to a homepage (optional).  the links for the core projects though should probably go to their project pages (e.g., http://*/specs/core-projects/networkx/ instead of github.com/networkx/networkx).  I like the simplicity of having one type of gallery, so maybe we should leave it as is.  Or maybe we should separate them and have them more customized for their purpose.  For example, we will want to use the people gallery on for other teams on the site.
- [ ] is there a better way to store data files that aren't going to be rendered pages?  For example, we don't really want `specs/steering-committee/matthias_bussonnier.md` rendered at this point.  Or if we are going to render it maybe we should add bios or something.

**Comment by jarrodmillman** [comment]
I think I got rid of the last bit of the old gallery stuff in #67.

**Comment by jarrodmillman** [comment]
@stefanv Question/Idea:  How hard would it be to also use `*.txt` files for the gallery.  For the core-projects, we would still have `core-projects/networkx.md` for instance; but for galleries where don't want a page per person, we could use `about/core/jarrod_millman.txt` for instance.

So far it seems like we don't want a page person for people galleries; but we do want a page per project for project galleries.  So maybe we do want to have two types of galleries.

**Comment by jarrodmillman** [comment]
- [ ] headers should include a field for the github history.  For example, for spec 0
https://github.com/scientific-python/specs/commits/main/spec-0000.md
- [ ] we will often want several authors.  so the author list in the headings should be comma separated instead of on separate lines as it is currently.  this should happen for SPECS and process docs.
- [ ] we should remove the date field.  Or we need to figure out what to use it for.

**Comment by stefanv** [comment]
> * [ ]  (low priority and maybe worth discussing) the links for the steering committee members should take you to their homepage or maybe like the nteract gallery I pointed to above they could have a link to github and to a homepage (optional).  the links for the core projects though should probably go to their project pages (e.g., http://*/specs/core-projects/networkx/ instead of github.com/networkx/networkx).  I like the simplicity of having one type of gallery, so maybe we should leave it as is.  Or maybe we should separate them and have them more customized for their purpose.  For example, we will want to use the people gallery on for other teams on the site.

This point is partially addressed; it now can switch between the internal page or GitHub.  It would be easy to add a homepage, just need to figure out where that should go, or whether that should replace the GH link.

**Comment by jarrodmillman** [comment]
@stefanv This is looking great!  Here is one more issue I noticed:

- [ ] The title now shows up for all process documents.  And the header is correctly rendered for `specs/purpose-and-process/index.md`, but the header is still missing from the rendered versions of `specs/steering-committee/_index.md` and `specs/core-projects/_index.md`.

**Comment by stefanv** [comment]
I don't see that problem:

![2021-02-16_09:55:58](https://user-images.githubusercontent.com/45071/108102271-2fab3f00-703d-11eb-8f8b-6a484eb01d6c.png)

**Comment by stefanv** [comment]
Fixed the heading problem in latest `main`.

**Comment by jarrodmillman** [comment]
It looks good to me.  I will open a new issue if I find anything else.  Anything that is missing from the above can be put off indefinitely.
