### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python.org#76]
- grant (due dates)
- conference (submissions, dates)
- community calls / developer meetings
- summits / meetings

**Comment by jarrodmillman** [comment]
Notes from Stefan:

> Google downloads external iCal calendars twice a day, so I think this would work well for us.  We can just host a bunch of ical files on our static site.  Then we can use something like this to build those files:
> - https://opendev.org/opendev/yaml2ical/src/branch/master/README.rst
> - https://github.com/ics-py/ics-py

> Emacs also has a converter from its very concise diary format to ical: https://www.gnu.org/software/emacs/manual/html_node/emacs/Format-of-Diary-File.html

**Comment by stefanv** [comment]
See https://github.com/scientific-python/yaml2ics

**Comment by jarrodmillman** [comment]
Closed by #191.
